global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alerting.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'

scrape_configs:
  - job_name: fluentd
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'fluentd:24231'
    metrics_path: /metrics